<?php
// module/Policy/view/policy/policy/delete.phtml:

$title = 'Delete policy';
$url   = $this->url('policy', ['action' => 'delete', 'id' => $id]);

$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>

<p>
    Are you sure that you want to delete Policy 
    <?= $this->escapeHtml($policy->policynumber) ?> by
    <?= $this->escapeHtml($policy->firstname) ?> <?= $this->escapeHtml($policy->lastname) ?>?
</p>

<form action="<?= $url ?>" method="post">
<div class="form-group">
    <input type="hidden" name="id" value="<?= (int) $policy->id ?>" />
    <input type="submit" class="btn btn-danger" name="del" value="Yes" />
    <input type="submit" class="btn btn-success" name="del" value="No" />
</div>
</form>